# Generated by Django 3.1.6 on 2021-02-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='remark',
            field=models.TextField(default='聚成报销', verbose_name='号码种类'),
        ),
    ]
